name: university_assignment_manager

description: University Assignment Manager Flutter app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.1.2
  shared_preferences: ^2.3.2
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icons/app_icon.png

flutter:
  uses-material-design: true
